_layouts/home.html
=> Update audience text

author/topics/install.adoc
Can’t push to this repo directly, here’s a PR with an addition to installation topic pointing out to manual gem install.
=> Add Full Manual to installation topic

author/topics/install.adoc
Lets wait for https://chocolatey.org/packages/metanorma/1.1.4 approvement first
=> [WIP] Update chocolatey installation steps

author/topics/document-format/requirements-recommendations-permissions.adoc
Documentation update, with requirements and part-of specified.
=> Doc update

author/csand/authoring.adoc, author/csd/authoring.adoc, author/ietf/ref/document-attributes.adoc, author/ietf/topics/markup.adoc, author/iso/ref/document-attributes.adoc, author/itu/authoring.adoc, author/m3d/authoring.adoc, author/ogc/authoring.adoc, author/ref/document-attributes.adoc, author/rsd/authoring.adoc, author/topics/document-format/text.adoc, author/unece/authoring.adoc
=> Docupdate20190517

_posts/2018-12-25-metanorma-on-windows-via-chocolatey.adoc
- https://github.com/metanorma/metanorma.com/issues/92
=> Remove wrong tip

author/iso/topics/content-validation.adoc
https://github.com/metanorma/metanorma-iso/issues/211
=> document ISO validations

author/itu/authoring.adoc, author/ref/document-attributes.adoc, author/topics/document-format/sections.adoc
https://github.com/metanorma/metanorma-standoc/issues/28
=> clauses can have language and script

author/iso/topics/markup.adoc, author/topics/document-format/bibliography.adoc
Recent updates from https://github.com/metanorma/isodoc/issues/114
=> Document bibliography reordering & renumbering

_layouts/home.html
Add IEC to front page, follow up on #117
=> Add IEC to front page

author/iec.adoc, author/ogc/ogc-hongkong.txt
Update IEC content according to https://github.com/metanorma/metanorma-standoc/issues/105
=> Update IEC translated-form usage

author/iso/ref/document-attributes.adoc
https://github.com/metanorma/metanorma.com/issues/116
=> restrictions in stages of ISO

author/iso/topics/markup.adoc
Cross-referencing testing: Bibliography subsection.
=> crossreference #115

author/iso/topics/markup.adoc
cross-linking Terms and definitions
=> Update markup.doc #115

author/ietf/topics/output-formats.adoc
=> output formats #115

author/iso/ref/document-attributes.adoc
cross-linking document attributes
=> Update document-attributes.adoc #115

author/gb/topics/output-formats.adoc
=> cross-linking output formats #115

author/ietf/topics/references.adoc
cross-linking References & Bibliography
=> references #115

author/rsd/authoring.adoc
cross-linking document attributes
=> cross-linking document attributes #115

author/csd/authoring.adoc
cross-linking document attributes and terms and definitions
=> document attributes, terms and definitions #115

author/unece/authoring.adoc
cross-linking Document Attributes
=> document attributes #115

author/ogc/authoring.adoc
cross-linking:
- Document Attributes
- Requirement, Recommendation, and Permission blocks
=> document attributes, recommendations #115

author/topics/building/reference-lookup.adoc
Update reference lookup page for citing bib items in override data cache #160
=> Update reference lookup page

.github/workflows/deploy-master.yml
=> metanorma/metanorma-cli#121 Add repository_dispatch event

_posts/2019-12-11-tex2mn-ietf.adoc, _posts/2019-12-13-tex2mn-ietf.adoc
This closes metanorma/tex2mm#72
@ronaldtse please review this. I also left a TODO for you to add a catchy phrase at the top.
=> Write post to showcase tex2mn

builder/topics/simple-adoption.adoc
metanorma/metanorma.com#217:
fix simple-adoption.adoc code snippet
=> Fix simple-adoption.adoc code snippet

author/topics/document-format/bibliography.adoc
Pending https://github.com/relaton/relaton.com/pull/9
=> Reference to asciibib

author/ogc/authoring.adoc
=> OGC updates

_posts/2020-01-06-metanorma-ietf-v2-released.adoc, author/iso/topics/markup.adoc, author/topics/document-format/bibliography.adoc, author/topics/document-format/section-terms.adoc, author/topics/document-format/text.adoc
https://github.com/metanorma/metanorma-standoc/issues/242
=> citation localities delimited with semicolon

author/topics/automation/yaml_to_text.adoc
metanorma/metanorma-standoc#261:
Changed yaml_to_text docs, added mention of file lookup
=> Additional docs for yaml2text block.

author/iso/topics/markup.adoc
metanorma/metanorma-iso#255: Documentation for new macro `term:[X,Y]`
=> New intelligent terms referencing

author/topics/document-format/text.adoc
As requested in https://github.com/metanorma/metanorma.com/issues/246
=> Add explanation for `eqnarray` disallowment

author/topics/document-format/bibliography.adoc
As requested in https://github.com/metanorma/metanorma.com/issues/296
=> Add note exception about IETF bibliography

_layouts/ietf-flavor.adoc
=> Update IETF build command

author/itu/authoring.adoc
https://github.com/metanorma/metanorma-itu/issues/144
=> ITU: recommendationnumber

_posts/2021-01-24-fonts-related-options-metanorma-cli.adoc
=> Add post about font-related metanorms-cli's arguments

author/topics/document-format/bibliography.adoc
=> no numeric references in normative refs: https://github.com/metanorma/metanorma-iso/issues/470

_pages/install.adoc
=> #402 update installation guide

author/topics/document-format/text.adoc
*Paragraph alignment* section  is duplicated (and misplaced). This PR fixes it.
=> Minor correction: Fix "Paragraph alignment" section title

author/topics/document-format/section-terms.adoc
*As requested in https://github.com/metanorma/metanorma-iso/issues/471#issuecomment-818889795*
=> Describe usage of `droploc%` flag when referring terms

author/iso/ref/document-attributes.adoc, author/iso/topics/markup.adoc
https://github.com/metanorma/metanorma.org/issues/422
=> document ISO subtype vocabulary

_posts/2021-05-17-metanorma-gsod-2021-writers.adoc
=> Post: new writers for GSoD 2021

_layouts/author-docs.html, _posts/2019-01-15-writing-metanorma-in-asciidoc-4.adoc, author/cc/authoring.adoc, author/iso/topics/markup.adoc, author/topics/document-format/section-terms.adoc
https://github.com/metanorma/metanorma-standoc/issues/468
=> concept/@noref, @noital

author/ogc/ref/document-attributes.adoc
https://github.com/metanorma/metanorma.org/issues/510
=> updated docstages: https://github.com/metanorma/metanorma.org/issues/510

author/ogc/ref/document-attributes.adoc
=> Add information about OGC new branding, fixes #513

README.adoc, _layouts/cc-flavor.adoc, _layouts/csa-flavor.adoc, _layouts/flavor.adoc, _layouts/gb-flavor.adoc, _layouts/iec-flavor.adoc, _layouts/iso-flavor.adoc, _layouts/itu-flavor.adoc, _layouts/m3aawg-flavor.adoc, _layouts/mpfa-flavor.adoc, _layouts/ogc-flavor.adoc, author/iec/topics/circulation-cover-page.adoc, author/iec/topics/formats.adoc, author/ogc/ref/document-attributes.adoc, author/ogc/topics/markup.adoc, author/topics/document-format/sections.adoc
=> OGC Exec Summary: https://github.com/metanorma/metanorma-ogc/issues/310

_layouts/iso-flavor.adoc, author/iso/ref/sts-mapping.adoc
=> Add MNXML to STS mapping

author/ref/document-attributes.adoc, author/topics/document-format/xrefs.adoc
=> index-terms: https://github.com/metanorma/metanorma-iso/issues/560

_posts/2021-08-26-pdf-accessibility-for-math-formulas.adoc, _posts/2021-09-03-accessibility-tagging-in-pdf.adoc, _posts/2021-12-04-pdf-protection.adoc, _software/packed-mn.adoc
@Intelligent2013 can you help add some content?
@opoudjis can you help review for https://github.com/metanorma/metanorma/issues/224 ?
=> Add PDF protection blog post

author/ref/document-attributes.adoc
=> PDF encryption: https://github.com/metanorma/metanorma/issues/224

_layouts/author-docs.html, author/topics/document-format/diagrams.adoc, author/topics/document-format/index.adoc, author/topics/document-format/xrefs.adoc
=> Split off indexing to a separate page

author/ogc/authoring-guide/metadata.adoc, author/topics/document-format/section-terms.adoc
=> Doc20211214

.github/workflows/build.yml, .github/workflows/links.yml
=> Add lychee as a link checker, fixes #107

author/topics/document-format/sections.adoc
=> Floating titles: https://github.com/metanorma/metanorma-bsi/issues/82

.github/workflows/build.yml, .github/workflows/deploy.yml, .github/workflows/links.yml, .lycheeignore, _pages/vcard-format-specification-rendered.html
=> Upgrade build to Ruby 3.1, fixes #542

_pages/install/cicd.adoc
- related to https://github.com/metanorma/ogc-citygml2/pull/5
=> Update links on cicd.adoc + add reference samples repo

author/ogc/ref/document-attributes.adoc
=> OGC contributors: https://github.com/metanorma/metanorma-ogc/issues/336

_layouts/ogc-flavor.adoc, author/ogc/authoring-guide.adoc, author/ogc/authoring-guide/bibliographic-references.adoc, author/ogc/authoring-guide/sections-ogc.adoc, author/ogc/authoring-guide/terms.adoc, author/ogc/topics/markup.adoc, author/ref/document-attributes.adoc
=> OGC annex sorting: https://github.com/metanorma/metanorma-ogc/issues/342

author/topics/document-format/collections.adoc
=> embed macro: https://github.com/metanorma/metanorma-bsi/issues/2

author/topics/document-format/text.adoc
=> retract ol typing: https://github.com/metanorma/metanorma-ogc/issues/359

author/iso/ref/document-attributes.adoc
=> Update stage codes according to metanorma/pubid-iso#36

author/topics/document-format/bibliography.adoc
=> std-link:[]: https://github.com/metanorma/metanorma-standoc/issues/547

_pages/install/cicd.adoc, _pages/install/linux.adoc, _pages/install/macos.adoc, _pages/install/windows.adoc
=> #569 add reference to metanorma-cli usage page

builder/topics/adopting-toolchain.adoc, builder/topics/simple-adoption.adoc, builder/topics/styling-output-html.adoc, builder/topics/styling-output-msword.adoc
- metanorma/metanorma-docker#119
- NO Breaking changes (list related PRs)
- NO Documentation update required ([create task for this](https://github.com/metanorma/metanorma.org/issues/new))
- NO External dependency introduced ([documentation update need](https://github.com/metanorma/metanorma.org/issues/new))
- NO Gem with native library introduced
=> metanorma/metanorma-docker#119 replace references to *.scss with *.css

author/topics/document-format/section-terms.adoc, author/topics/document-format/text.adoc
=> case concepts: https://github.com/metanorma/metanorma-iso/issues/617

author/iso/ref/document-attributes.adoc, author/iso/topics/markup.adoc
=> editorial notes: https://github.com/metanorma/metanorma.org/issues/599

author/topics/document-format/bibliography.adoc
*As per https://github.com/metanorma/metanorma.org/issues/583*
=> Add content about numeric references with automatic fetching

_pages/install.adoc, _pages/install/docker.adoc, _pages/install/linux.adoc, _pages/install/macos.adoc, _pages/install/man.adoc, _pages/install/manual-installation.adoc, _pages/install/usage.adoc, _pages/install/windows.adoc
=> Doc20220602

author/topics/document-format/text.adoc
Fixes https://github.com/metanorma/metanorma.org/issues/617
=> Add encoding guidance for numeric ranges

author/ogc/topics/requirements.adoc
=> feat: use /conf/ prefix for OGC modspec conformance tests, fixes #620

author/topics/document-format/changes.adoc, author/topics/document-format/text.adoc
=> move corrigenda

_posts/2022-07-11-metanorma-collection-si-brochure.adoc
=> #626 update commands to support windows too

_layouts/mpfa-flavor.adoc, _pages/flavors.adoc, _pages/install.adoc, _pages/install/man.adoc, _pages/install/usage.adoc, _posts/2018-12-16-writing-metanorma-in-asciidoc-3.adoc, _posts/2019-04-26-metanorma-templates-and-metanorma-new.adoc, _software/packed-mn.adoc, author/cc/authoring.adoc, author/mpfa/authoring.adoc, builder/topics/localization.adoc
Related:
- https://github.com/metanorma/SWF-Corpus_and_IEEEP2874-D2/pull/6#issuecomment-1181389204
=> Steps to install non-default metanorma-* processors

author/topics/document-format/text.adoc
=> span style: https://github.com/metanorma/metanorma-standoc/issues/647

author/ieee/ref/document-attributes.adoc, author/ref/document-attributes.adoc
=> document-scheme: https://github.com/metanorma/metanorma-ieee/issues/117

_posts/2021-08-26-pdf-accessibility-for-math-formulas.adoc, author/ogc/topics/requirements.adoc, author/topics/document-format/requirements.adoc
=> Modspec update: https://github.com/metanorma/metanorma-ogc/issues/398

_posts/2022-08-22-annotations-available-in-all-ouputs.adoc, author/topics/document-format/annotations.adoc
=> Doc20220822 fix

_layouts/ieee-flavor.adoc, author/ieee/ref/document-attributes.adoc, author/ieee/topics/formats.adoc
=> IEEE XML: https://github.com/metanorma/metanorma-ieee/issues/132

_layouts/ogc-flavor.adoc, author/ieee/topics/formats.adoc, author/ietf/ref/document-attributes.adoc, author/ietf/topics/markup.adoc, author/iso/topics/formats.adoc, author/itu/topics/markup.adoc, author/ogc/ref/document-attributes.adoc, author/ogc/topics/markup.adoc, author/topics/automation/datamodel.adoc, author/topics/automation/json_to_text.adoc, author/topics/automation/yaml_to_text.adoc, author/topics/document-format/collections.adoc, author/topics/document-format/indexes.adoc, author/topics/document-format/requirements-modspec.adoc, author/topics/document-format/sections.adoc, author/topics/document-format/text.adoc, author/topics/document-format/xrefs.adoc, author/topics/languages.adoc, author/un/authoring.adoc
=> Update example syntax and some documentation fixes

author/ref/document-attributes.adoc, author/topics/document-format/xrefs.adoc
=> xrefstyle: https://github.com/metanorma/metanorma-ogc/issues/330

author/topics/document-format/bibliography.adoc
=> dl formatting: https://github.com/relaton/relaton-bib/issues/64

author/topics/document-format/bibliography.adoc
=> erefstack: https://github.com/metanorma/metanorma-standoc/issues/691

author/iso/ref/document-attributes.adoc, author/itu/topics/markup.adoc, author/ref/document-attributes.adoc
- Added note about ISO titles with multiple components.
- Minor markup fixes.
=> Add note about ISO titles with multiple components

author/iso/ref/document-attributes.adoc
=> chore: update iso document attributes formatting

author/ref/document-attributes.adoc, author/topics/document-format/requirements-modspec.adoc
=> Modspec Identifier bases

author/ieee/authoring-guide/cross-references.adoc, author/ogc/authoring-guide/cross-references.adoc
=> fix: fix bib links in tutorials, fixes #679

_posts/2022-12-28-relaton-doi.adoc
=> Blog post on relaton-doi

_posts/2022-11-17-xmlsts-to-metanorma.adoc
chore: update xmlsts blog post
=> chore: update xmlsts blog post

author/ieee/authoring-guide/terms-definitions.adoc
=> https://github.com/metanorma/metanorma-ieee/issues/81

author/iso/topics/markup.adoc
=> Doc20230126

author/iec/ref/document-attributes.adoc, author/iso/ref/document-attributes.adoc
=> Doc20201127

author/ref/document-attributes.adoc
=> Doc20210322 2

author/topics/sections/bibliography.adoc
=> date.accessed: https://github.com/metanorma/metanorma-iso/issues/1114

author/itu/ref/document-attributes.adoc, author/ref/document-attributes.adoc
=> Doc20240307 itu

_layouts/author-docs.html, author/basics/cross-references.adoc, author/basics/xrefs.adoc, author/bsi.adoc, author/bsi/topics/markup.adoc, author/ieee/authoring-guide/cross-references.adoc, author/iho/authoring-guide/cross-references.adoc, author/iho/topics/markup.adoc, author/iso/topics/markup.adoc, author/itu/ref/document-attributes.adoc, author/nist/topics/markup.adoc, author/ogc/authoring-guide/cross-references.adoc, author/ogc/authoring-guide/metadata.adoc, author/topics/blocks/lists.adoc, author/topics/document-format/xrefs.adoc, author/topics/inline_markup/links.adoc, learn/lessons/lesson-2-4-3.adoc
=> Doc20240323

_pages/install/docker.adoc, _posts/2021-01-24-fonts-related-options-metanorma-cli.adoc
=> fix: font management links

_posts/2024-04-04-ogc-modspec-in-yaml.adoc
=> edit suggestions

author/topics/collections.adoc
=> correction on collections

_layouts/develop-docs.html
=> Fix broken links in sidebar of Develop page

author/iso/topics/markup.adoc, author/topics/blocks/figures.adoc, author/topics/blocks/tables.adoc
chore: split unit statements to figures and tables
=> chore: split unit statements to figures and tables

_layouts/ogc-flavor.adoc
=> fix sidebar links: https://github.com/metanorma/metanorma-ogc/issues/660

author/topics/collections.adoc
=> Doc20240428

_config.yml, custom-intro.html, flavor-quickstart-steps.adoc
=> Changing the Metanorma slogan

_posts/2021-03-26-metanorma-gsod-2021.adoc, author/ieee/ref/document-attributes.adoc, author/nist/topics/markup.adoc, author/topics/inline_markup/semantic-elements.adoc, author/topics/metadata/contributor.adoc
=> Update semantic elements

author/topics/sections/attachments.adoc
=> Attachments page updated for metanorma/mn-native-pdf#739

author/topics/automation/datamodel.adoc, author/topics/automation/json_to_text.adoc, author/topics/automation/lutaml_uml.adoc, author/topics/automation/yaml_to_text.adoc
As requested in https://github.com/metanorma/metanorma.org/issues/723
=> Correct typos and writing inconsistencies in Lutaml articles

author/topics/inline_markup/semantic-elements.adoc, author/topics/languages.adoc
=> Describe `number` command in localization page as well

author/topics/inline_markup/semantic-elements.adoc
=> date command example syntax updated, metanorma/isodoc#645

author/topics/document-format/page-flow.adoc
=> feat: provide simple page break syntax

author/ietf/topics/markup.adoc, author/topics/blocks/passthroughs.adoc, author/topics/blocks/tables.adoc, author/topics/collections/configuration.adoc, author/topics/output/validation.adoc
=> table styles: https://github.com/metanorma/metanorma/issues/446

_posts/2024-04-12-metanorma-cli-1.9.6-release.adoc, _posts/2024-04-22-metanorma-cli-1.9.7-release.adoc, _posts/2024-05-07-metanorma-cli-1.9.8-release.adoc, _posts/2024-06-04-metanorma-cli-1.10.0-release.adoc, _posts/2024-06-18-metanorma-cli-1.10.1-release.adoc, _posts/2024-07-09-metanorma-cli-1.10.2-release.adoc, _posts/2024-07-22-metanorma-cli-1.10.3-release.adoc, _posts/2024-08-07-metanorma-cli-1.10.4-5-release.adoc, _posts/2024-08-20-metanorma-cli-1.10.6-release.adoc, _posts/2024-09-02-metanorma-cli-1.10.7-release.adoc, _posts/2024-09-16-metanorma-cli-1.10.8-release.adoc, _posts/2024-09-30-metanorma-cli-1.10.9-release.adoc, _posts/2024-10-15-metanorma-cli-1.10.10-release.adoc, _posts/2024-10-28-metanorma-cli-1.10.11-release.adoc, _posts/2024-11-08-line-numbers.adoc, _posts/2024-11-12-metanorma-cli-1.11.0-release.adoc, _posts/2024-11-17-metanorma-cli-1.11.1-release.adoc, _posts/2024-12-12-metanorma-cli-1.11.2-release.adoc, _posts/2024-12-25-metanorma-cli-1.11.3-release.adoc, _posts/2025-01-09-metanorma-cli-1.11.4-release.adoc, _posts/2025-01-28-metanorma-cli-1.11.5-release.adoc, _posts/2025-03-21-metanorma-windows-docker.adoc, author/topics/document-format/page-flow.adoc
=> Add release posts

_pages/install/site.adoc
=> chore(site): Add examples of specifying site manifest file as first argument

_pages/install/site.adoc
=> chore(site): Fix internal links

author/topics/collections/configuration.adoc, author/topics/sections/extension-container.adoc, author/topics/troubleshooting.adoc
=> doc20250522

_posts/2025-04-22-data2text.adoc
=> Blog post for data2text

_posts/2025-07-03-introducing-metanorma-tools.adoc
=> feat: add blog post for metanorma tools figure extraction
